# Generated by Django 5.2 on 2025-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_created=True, auto_now=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                ("id_no", models.IntegerField(max_length=8)),
                ("phone_number", models.BigIntegerField(max_length=10)),
                ("kra_pin", models.CharField()),
                ("drivin_licence", models.CharField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
