# Generated by Django 5.2 on 2025-04-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.BigIntegerField(),
        ),
    ]
