# Generated by Django 5.2 on 2025-04-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id_no",
            field=models.IntegerField(),
        ),
    ]
